server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: USER-SERVICE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-48449289.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            clientId: 0oa8ursanwZrHJWEe5d7
            clientSecret: DO9LrlaTFvWof-L3JjxjQPveDYPIUB0ARyoJoxBz
        provider:
          okta:
            issuerUri: https://dev-48449289.okta.com/oauth2/default


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 3s

okta:
  oauth2:
    issuer: https://dev-48449289.okta.com/oauth2/default
    audience: api://default
